pipeline:

  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=staging
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=production
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  unit_test:
    image: quay.io/ukhomeofficedigital/cop-node:12-alpine
    commands:
      - node -v
      - npm -v
      - npm ci
      - npm run test
    when:
      event: push

  linting:
    image: quay.io/ukhomeofficedigital/cop-node:12-alpine
    commands:
      - npm run lint -- .
    when:
      event: push

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t sgmr-service:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  vulnerability-scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile
    image_name: sgmr-service:${DRONE_COMMIT_SHA}
    local_image: true
    tolerate: low
    fail_on_detection: false
    when:
      branch: master
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: QUAY_PASSWORD
        target: DOCKER_PASSWORD
      - source: QUAY_USERNAME
        target: DOCKER_USERNAME
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sgmr-service
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: DEV_KUBE_NAMESPACE_COP_SGMR
      target: KUBE_NAMESPACE
    - source: DEV_KUBE_SERVER
      target: KUBE_SERVER
    - source: DEV_SGMR_DATA_API_BASE_URL
      target: SGMR_DATA_API_BASE_URL
    - source: DEV_SGMR_SERVICE_URL
      target: SGMR_SERVICE_URL
    - source: DEV_SGMR_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: SGMR_SERVICE_IMAGE
      target: SGMR_SERVICE_IMAGE
    - source: SGMR_SERVICE_NAME
      target: SGMR_SERVICE_NAME
    - source: SGMR_SERVICE_PORT
      target: SGMR_SERVICE_PORT
    - source: DEV_WHITELIST
      target: WHITELIST
    commands:
      - export SGMR_SERVICE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: STAGING_KUBE_NAMESPACE_COP_SGMR
      target: KUBE_NAMESPACE
    - source: STAGING_KUBE_SERVER
      target: KUBE_SERVER
    - source: STAGING_SGMR_DATA_API_BASE_URL
      target: SGMR_DATA_API_BASE_URL
    - source: STAGING_SGMR_SERVICE_URL
      target: SGMR_SERVICE_URL
    - source: STAGING_SGMR_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: SGMR_SERVICE_IMAGE
      target: SGMR_SERVICE_IMAGE
    - source: SGMR_SERVICE_NAME
      target: SGMR_SERVICE_NAME
    - source: SGMR_SERVICE_PORT
      target: SGMR_SERVICE_PORT
    - source: STAGING_WHITELIST
      target: WHITELIST
    commands:
      - export SGMR_SERVICE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
    - source: PRODUCTION_KUBE_NAMESPACE_COP_SGMR
      target: KUBE_NAMESPACE
    - source: PRODUCTION_KUBE_SERVER
      target: KUBE_SERVER
    - source: PRODUCTION_SGMR_DATA_API_BASE_URL
      target: SGMR_DATA_API_BASE_URL
    - source: PRODUCTION_SGMR_SERVICE_URL
      target: SGMR_SERVICE_URL
    - source: PRODUCTION_SGMR_KUBE_TOKEN
      target: KUBE_TOKEN
    - source: NGINX_IMAGE
      target: NGINX_IMAGE
    - source: NGINX_TAG
      target: NGINX_TAG
    - source: SGMR_SERVICE_IMAGE
      target: SGMR_SERVICE_IMAGE
    - source: SGMR_SERVICE_NAME
      target: SGMR_SERVICE_NAME
    - source: SGMR_SERVICE_PORT
      target: SGMR_SERVICE_PORT
    - source: PRODUCTION_WHITELIST
      target: WHITELIST
    commands:
      - export SGMR_SERVICE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
