---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .NAME }}"
type: Opaque
data:
  cypress_cache_folder: "{{.CYPRESS_CACHE_FOLDER | b64enc}}"
  kube_namespace: "{{.KUBE_NAMESPACE | b64enc}}"
  mailslurp_api_key: "{{.MAILSLURP_API_KEY | b64enc}}"
  cypress_key: "{{.CYPRESS_KEY | b64enc}}"
