---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .NAME }}"
type: Opaque
data:
  cypress_cache_folder: "{{.CYPRESS_CACHE_FOLDER | b64enc}}"
  kube_namespace: "{{.KUBE_NAMESPACE | b64enc}}"
  mailslurp_api_key: "{{.MAILSLURP_API_KEY | b64enc}}"
  cypress_key: "{{.CYPRESS_KEY | b64enc}}"
  report_base_url: "{{.REPORT_BASE_URL | b64enc}}"
  slack_web_hook: "{{.SLACK_WEB_HOOK | b64enc}}"
  s3_bucket_name: "{{.S3_BUCKET_NAME | b64enc}}"
  s3_access_key: "{{.S3_ACCESS_KEY | b64enc}}"
  s3_secret_key: "{{.S3_SECRET_KEY | b64enc}}"
  auth_realm: "{{.AUTH_REALM | b64enc}}"
